# Generated by Django 3.2.23 on 2023-11-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0002_alter_destination_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='placenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='picture')),
                ('month', models.DateField()),
            ],
        ),
    ]
