# Generated by Django 3.2.23 on 2023-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_app', '0003_placenew'),
    ]

    operations = [
        migrations.AddField(
            model_name='placenew',
            name='desc',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
